const changeTypes = ["bullet-swap", "bullet-rewrite", "skill", "project-swap", "summary"];

export const semanticGoldenFixtures = [
  { id: "backend-api", baseResumeId: "swe-cloud", job: "Backend engineer building Python REST APIs with PostgreSQL and Redis.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:python", "skill:postgresql", "skill:redis"] }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["Rust"] } },
  { id: "full-stack", baseResumeId: "swe-cloud", job: "Full stack engineer using React, TypeScript, Node.js, and REST APIs.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:react", "skill:typescript", "skill:node.js"] }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["Angular"] } },
  { id: "cloud-platform", baseResumeId: "swe-cloud", job: "Platform engineer using AWS, Docker, Kubernetes, and CI/CD.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:aws", "skill:docker", "skill:kubernetes"] }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["Azure production ownership"] } },
  { id: "ai-rag", baseResumeId: "ai", job: "AI engineer delivering retrieval augmented generation and document retrieval systems in Python.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["servbeyond-proposal-assistant", "skill:python"] }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["CUDA kernel authoring"] } },
  { id: "llm-infrastructure", baseResumeId: "ai", job: "Build production LLM inference and serving infrastructure with performance evaluation.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["runara-speculative-decoding"] }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["2 to 3 times benchmark ownership"] } },
  { id: "react-native-mobile", baseResumeId: "mobile", job: "Mobile engineer shipping React Native and TypeScript products with WebRTC.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:react-native", "skill:typescript", "skill:webrtc"] }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["native iOS ownership"] } },
  { id: "strong-match-no-change", baseResumeId: "mobile", job: "React Native TypeScript Redux Toolkit WebRTC mobile development.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:react-native", "skill:typescript"] }], unsupported: [], allowedChangeTypes: [], forbiddenClaims: [] } },
  { id: "unsupported-technology", baseResumeId: "swe-cloud", job: "Must have production Rust and Elixir experience.", expected: { requirements: [], unsupported: ["Rust", "Elixir"], allowedChangeTypes: [], forbiddenClaims: ["Rust", "Elixir"] } },
  { id: "or-requirement", baseResumeId: "swe-cloud", job: "Requires Python or JavaScript/TypeScript.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:python", "skill:javascript", "skill:typescript"], alternatives: true }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: ["Python or JavaScript/TypeScript skill"] } },
  { id: "composite-and", baseResumeId: "swe-cloud", job: "Requires SQL and document-store schema design.", expected: { requirements: [{ priority: "must", validEvidenceIds: ["skill:sql", "skill:mongodb", "xelpmoc-sql-redis"], composite: true }], unsupported: [], allowedChangeTypes: changeTypes, forbiddenClaims: [] } },
  { id: "knowledge-only", baseResumeId: "swe-cloud", job: "GCP familiarity is preferred; production GCP implementation is not required.", expected: { requirements: [{ priority: "preferred", validEvidenceIds: ["skill:google-cloud-platform-gcp"], status: "knowledge-only" }], unsupported: [], allowedChangeTypes: ["skill"], forbiddenClaims: ["implemented GCP", "shipped on GCP"] } },
  { id: "eligibility-blockers", baseResumeId: "swe-cloud", job: "U.S. citizenship is required. An active security clearance is required. Candidates on CPT or OPT are not accepted.", expected: { requirements: [], unsupported: [], blockers: ["citizenship requirement", "security-clearance requirement", "explicit CPT or OPT rejection"], allowedChangeTypes: [], forbiddenClaims: [] } },
];

export const semanticGoldenChangeTypes = changeTypes;
